services:
  # Radarr - Gerenciador de Filmes
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - volume_radarr:/config
      - volume_filmes:/movies
      - volume_downloads:/downloads
    restart: unless-stopped
    networks:
      - proxy
      - media
      - monitoring
    depends_on:
      - prowlarr
      - qbittorrent
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.homelab`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.docker.network=proxy"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G

networks:
  media:
    driver: bridge
    name: media
  proxy:
    driver: bridge
    name: proxy
  monitoring:
    driver: bridge
    name: monitoring

volumes:
  volume_radarr:
    external: true
  volume_filmes:
    external: true
  volume_downloads:
    external: true